### ISSUE TITLE
[Android/iOS] Cannot locate MergedResourcesDictionnary.xaml with latest dev uno.ui on project with pages on UWP head

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno.xamlmerge.task#90]
## Current behavior

It doesn't localize MergedResourcesDictionnary.xaml. Which makes the app crash.
![image](https://user-images.githubusercontent.com/17461593/197287230-5f4b4155-9ce1-49e8-9c78-72dde5f520c4.png)

## Expected behavior

It should be able to find the MergedResourcesDictionnary.xaml. It works still when using an older uno.ui package version (e.g **4.4.20**).

![Screenshot_20221021-170916](https://user-images.githubusercontent.com/17461593/197289277-e0740d11-a616-4421-a343-0e392531734e.jpg)

## How to reproduce it (as minimally and precisely as possible)

- Download this sample [MergeDictionnaries.zip](https://github.com/unoplatform/uno.xamlmerge.task/files/9842447/MergeDictionnaries.zip)
- Deploy on android/iOS

## Environment

Nuget Package:

Package Version(s):
**uno.ui:** 4.6.0-dev.888
**uno.xamlmerge.ui:** 1.1.0-dev.13

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] ~~WebAssembly~~
- [ ] ~~WebAssembly renders for Xamarin.Forms~~
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022 (version: 17.3.5)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

- In the sample, the project is set up so all xaml files goes in the UWP, to keep the UWP hot reload feature on our project. 
- If you first rebuild the UWP project, then it won't crash anymore on Android/iOS.
  - You can then delete the generated MergedResourcesDictionnary file to reproduce the crash again.

**Comment by jeromelaban** [comment]
@takla21 the original project solution is built to avoid the reuse of files this way (this is not needed anymore), changing files location is likely to cause this issue.

**Comment by takla21** [comment]
@jeromelaban right, I did validated on my side that the bug does not happen when starting directly from the app template (shared project). The problem here, as mentioned in the OP, is that we have to put the .xaml file in order to keep the UWP hotreload on more complex project. So we're restricted to this structure until it's fixed (or move our project into WinUI maybe?).

**Comment by jeromelaban** [comment]
Got it. Know that this is fixed in VS since 17.2, so you should be good to go. Still, we'll take a look.

**Comment by jeromelaban** [comment]
Fixed in Uno.XamlMerge.Task 1.14.0-dev.14.

**Comment by takla21** [comment]
Unfortunately, the bug still happens on 1.14.0-dev.14. I've updated the sample with the latest uno.xamlmerge version and also latest uno dev (except for iOS, there's another issue I've found that I'm going to trace separately)

[MergeDictionnaries_update.zip](https://github.com/unoplatform/uno.xamlmerge.task/files/10071140/MergeDictionnaries_update.zip)

Note: this also keeps popping when using this version of uno.xamlmerge

**Comment by takla21** [comment]
I've attempted to debug the vs prompt mentionned in my other comment (by pressing ok). Essentially, it thrown this

![image](https://user-images.githubusercontent.com/17461593/203437276-a8122f33-ecc6-4f2b-a068-56cf78b73726.png)

**Comment by jeromelaban** [comment]
This looks unrelated. Make sure to restart visual studio once you've updated the package.

**Comment by jeromelaban** [comment]
Ah no, it's missing break, I'll remove the change, apologies about the delay.

**Comment by jeromelaban** [comment]
@takla21 1.15.0-dev.15 contains the proper fixes. Let me know if it helps, thanks!

**Comment by takla21** [comment]
@jeromelaban So the good news is that it works on iOS. Unfortunately, it's still the same issue on android. Although the visual studio prompt is not shown anymore.

I've updated the sample again with 1.15.0-dev.15 here  [MergeDictionnaries_1.15.0-dev.15.zip](https://github.com/unoplatform/uno.xamlmerge.task/files/10076175/MergeDictionnaries_1.15.0-dev.15.zip)

I've generated a binlog for android. hopefully it can help
[msbuild.zip](https://github.com/unoplatform/uno.xamlmerge.task/files/10076244/msbuild.zip)

**Comment by jeromelaban** [comment]
Ah I see, the build was not the right one... it's in 1.16.0-dev.16 that should be used. 

That being said, all this happened because Xamarin projects by default use `Uno.SourceGenerationTasks`, and if you set the `<UnoUIUseRoslynSourceGenerators>true</UnoUIUseRoslynSourceGenerators>` it will use Roslyn instead and build a lot faster. This is enabled by default for net6+ projects.

If you can use this if your build agents are running msbuild 17.0 or later.

**Comment by takla21** [comment]
Now, it's working on all platforms. I'll also take a look to the suggestion to use `UnoUIUseRoslynSourceGenerators` as we're definitely using msbuild 17.0 on our pipelines. 

Thanks!
